### ISSUE TITLE
Package rrd setup failed

### ISSUE THREAD

**Issue by fmobile999** [dgomes/rrd_recorder#8]
Great (!) thanks for you job!!! RRD is a great tool for me and well known (i don't like influx and grafana).

But in HA 2021.5.3 i got error:

`Package rrd setup failed. Component rrd Error loading shared library librrd.so.8: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/rrdtool.cpython-38-x86_64-linux-gnu.so)`

Is it possible to run rrd_recorder?

**Comment by dgomes** [comment]
library is missing from OS

You can install it like so from your command line:

```
docker exec -it home-assistant /bin/bash

apk add build-base rrdtool-dev ttf-dejavu
pip3 install --user --no-cache-dir --prefix= --no-dependencies rrdtool
```

**Comment by fmobile999** [comment]
It's all installed allready
```
~ $ apk add build-base rrdtool-dev ttf-dejavu
OK: 406 MiB in 170 packages
~ $ pip3 install --user --no-cache-dir --prefix= --no-dependencies rrdtool
Requirement already satisfied: rrdtool in /usr/lib/python3.8/site-packages (0.1.15)
```

**Comment by fmobile999** [comment]
Ooh, yeeah!!
Thanks! Docker exec - works, instead ssh terminal.

**Comment by fmobile999** [comment]
Sorry, but I have new problem.

When rrd file contain more 2 DS, it cause error in camera component:

```
 2021-05-18 18:16:17 DEBUG (SyncWorker_8) [custom_components.rrd.camera] Setup RRD Graph test_test
2021-05-18 18:16:17 DEBUG (SyncWorker_8) [custom_components.rrd.camera] Added graph DEF:Ampa=rrd/test.rrd:ampa:AVERAGE
2021-05-18 18:16:17 DEBUG (SyncWorker_8) [custom_components.rrd.camera] Added graph DEF:Ampb=rrd/test.rrd:ampb:AVERAGE
2021-05-18 18:16:17 DEBUG (SyncWorker_8) [custom_components.rrd.camera] Added graph DEF:Volta=rrd/test.rrd:volta:AVERAGE
```
after it:

```
2021-05-18 18:16:17 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...tasks.py:885]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.8/asyncio/futures.py:354
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/asyncio/futures.py", line 356, in _set_state
    _copy_future_state(other, future)
  File "/usr/local/lib/python3.8/asyncio/futures.py", line 332, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```
and camera error 

```
2021-05-18 18:16:27 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform rrd is taking over 10 seconds.
2021-05-18 18:17:17 ERROR (MainThread) [homeassistant.components.camera] Setup of platform rrd is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```
Last test config:
```
rrd:
  path: 'rrd'
  databases:
    - name: test
      step: 30s
      data_sources:
        - sensor: sensor.amp_a
          name: ampa
          cf: GAUGE
          heartbeat: 300
        - sensor: sensor.amp_b
          name: ampb
          cf: GAUGE
          heartbeat: 300
        - sensor: sensor.voltage_a
          name: volta
          cf: GAUGE
          heartbeat: 300
        - sensor: sensor.voltage_b
          name: voltb
          cf: GAUGE
          heartbeat: 300
        - sensor: sensor.voltage_c
          name: voltc
          cf: GAUGE
          heartbeat: 300

      round_robin_archives:
        - cf: AVERAGE
          steps: 1m
          rows: 3d

camera:
  - platform: rrd
    name: test_test
    rrdfile: rrd/test.rrd
    timerange: 1d
    args:

    rrdgraph_options:   # Optional graph enhancements
```
What I do wrong?
With 2 DS in rrd file it works perfectly.

**Comment by fmobile999** [comment]
I understood it.
Iterator don't work (on my system, maybe)
return only 2 color values

` 64       color = iter(["#00FF00", "#0033FF"])`

and line 101 cause error

`101                            f"LINE1:{ds.capitalize()}{next(color)}:{ds.capitalize()}"`
